// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import GovukAccordionController from "./govuk_accordion_controller.js";
application.register("govuk-accordion", GovukAccordionController);

import GovukButtonController from "./govuk_button_controller.js";
application.register("govuk-button", GovukButtonController);

import GovukCharacterCountController from "./govuk_character_count_controller.js";
application.register("govuk-character-count", GovukCharacterCountController);

import GovukCheckboxesController from "./govuk_checkboxes_controller.js";
application.register("govuk-checkboxes", GovukCheckboxesController);

import GovukDetailsController from "./govuk_details_controller.js";
application.register("govuk-details", GovukDetailsController);

import GovukErrorSummaryController from "./govuk_error_summary_controller.js";
application.register("govuk-error-summary", GovukErrorSummaryController);

import GovukHeaderController from "./govuk_header_controller.js";
application.register("govuk-header", GovukHeaderController);

import GovukNotificationBannerController from "./govuk_notification_banner_controller.js";
application.register(
  "govuk-notification-banner",
  GovukNotificationBannerController
);

import GovukRadiosController from "./govuk_radios_controller.js";
application.register("govuk-radios", GovukRadiosController);

import GovukSkipLinkController from "./govuk_skip_link_controller.js";
application.register("govuk-skip-link", GovukSkipLinkController);

import GovukTabsController from "./govuk_tabs_controller.js";
application.register("govuk-tabs", GovukTabsController);
