name: Test

on:
  pull_request:

jobs:
  test:
    name: Rails
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-retries 5
          --health-timeout 5s
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/govuk_mockup_kit_test
      RAILS_ENV: test

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Add testing hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 this.app.local" | sudo tee -a /etc/hosts
      - run: bin/rails db:test:prepare
      - run: bin/rails assets:precompile
      - run: bin/test
